import fs from 'node:fs/promises';
import { NodeIO } from '@gltf-transform/core';
import { ALL_EXTENSIONS } from '@gltf-transform/extensions';
import { dedup, weld, meshopt } from '@gltf-transform/functions';
import { MeshoptEncoder, MeshoptDecoder } from 'meshoptimizer';
await Promise.all([MeshoptEncoder.ready,MeshoptDecoder.ready]);
const io=new NodeIO().registerExtensions(ALL_EXTENSIONS).registerDependencies({'meshopt.encoder':MeshoptEncoder,'meshopt.decoder':MeshoptDecoder});
const path=new URL('../public/models/subaru-xv-inspection.glb',import.meta.url).pathname;
const before=(await fs.stat(path)).size,doc=await io.read(path);
const names=doc.getRoot().listNodes().filter(n=>n.getName().startsWith('part-')).map(n=>n.getName()).sort();
await doc.transform(dedup(),weld(),meshopt({encoder:MeshoptEncoder,level:'high'}));
const bytes=await io.writeBinary(doc);const restored=await io.readBinary(bytes);
const afterNames=restored.getRoot().listNodes().filter(n=>n.getName().startsWith('part-')).map(n=>n.getName()).sort();
if(names.length!==32||JSON.stringify(names)!==JSON.stringify(afterNames))throw Error('Optimization changed component identity');
await fs.writeFile(path,bytes);
const metaPath=new URL('../public/models/model-metadata.json',import.meta.url);const meta=JSON.parse(await fs.readFile(metaPath,'utf8'));meta.glb_bytes=bytes.length;meta.uncompressed_glb_bytes=before;meta.compression='EXT_meshopt_compression; all 32 component identities retained';await fs.writeFile(metaPath,JSON.stringify(meta,null,2)+'\n');
console.log(`Model optimized: ${(before/1048576).toFixed(2)} MB → ${(bytes.length/1048576).toFixed(2)} MB; ${names.length} inspection components verified.`);
