import { useEffect, useRef, useState } from 'react';
import { Camera, Upload, X, RotateCcw, Check, AlertCircle } from 'lucide-react';
import { CHECKS, checkById } from './checklist';
import { uid, now, type RecordData, type Photo } from './domain';
export default function CameraModal({record,checkId,initialFindingId,onClose,onSave,captureSignal,voiceAction,autoOpen=false}:{record:RecordData;checkId:string;initialFindingId?:string;onClose:()=>void;onSave:(p:Photo)=>void;captureSignal:number;voiceAction?:{id:number;action:'capture'|'save'|'retake'};autoOpen?:boolean}){
 const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),input=useRef<HTMLInputElement>(null),[preview,setPreview]=useState(''),[name,setName]=useState(''),[error,setError]=useState(''),[ready,setReady]=useState(false),[loading,setLoading]=useState(false),[target,setTarget]=useState(checkId),[finding,setFinding]=useState(initialFindingId??'');
 const stop=()=>{stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;setReady(false);};
 useEffect(()=>()=>stream.current?.getTracks().forEach(t=>t.stop()),[]);
 useEffect(()=>{if(!autoOpen)return;const timer=setTimeout(()=>{void openCamera();},0);return()=>clearTimeout(timer);},[]);
 async function openCamera(){setError('');setLoading(true);try{if(!navigator.mediaDevices?.getUserMedia)throw Error('Camera capture is unavailable in this browser. Upload an existing photo.');stream.current?.getTracks().forEach(t=>t.stop());const media=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1600}},audio:false});if(!video.current){media.getTracks().forEach(t=>t.stop());return;}stream.current=media;video.current.srcObject=media;await video.current.play();setReady(true);}catch(e){setError(e instanceof Error?`${e.name}: ${e.message}. Your notes are safe; you can upload a photo instead.`:'Camera unavailable. Upload a photo instead.');}finally{setLoading(false);}}
 function capture(){if(!ready||!video.current?.videoWidth){setError('Open the camera and wait for the preview before capturing.');return;}const v=video.current;const canvas=document.createElement('canvas');canvas.width=v.videoWidth;canvas.height=v.videoHeight;canvas.getContext('2d')!.drawImage(v,0,0);setPreview(canvas.toDataURL('image/jpeg',.82));setName(`Capture ${new Date().toLocaleTimeString()}.jpg`);stop();}
 const lastSignal=useRef(captureSignal);useEffect(()=>{if(lastSignal.current!==captureSignal){lastSignal.current=captureSignal;capture();}},[captureSignal]);
 const lastVoiceAction=useRef(voiceAction?.id);
 useEffect(()=>{
  if(!voiceAction||voiceAction.id===lastVoiceAction.current)return;lastVoiceAction.current=voiceAction.id;
  if(voiceAction.action==='capture')capture();
  else if(voiceAction.action==='retake'){setPreview('');setError('');setTimeout(()=>{void openCamera();},0);}
  else if(preview&&!loading){onSave({id:uid(),checkId:target,findingId:finding||undefined,data:preview,name:name||checkById(target).name,createdAt:now()});onClose();}
  else setError('Take a photo before saving.');
 },[voiceAction?.id]);
 async function upload(file?:File){if(!file)return;setError('');if(!/^image\/(jpeg|png|webp|heic|heif)$/.test(file.type)){setError('Choose a JPEG, PNG, or WebP image.');return;}if(file.size>15*1024*1024){setError('Choose a photo smaller than 15 MB.');return;}setLoading(true);try{const bitmap=await createImageBitmap(file);const ratio=Math.min(1,1600/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=bitmap.width*ratio;canvas.height=bitmap.height*ratio;canvas.getContext('2d')!.drawImage(bitmap,0,0,canvas.width,canvas.height);setPreview(canvas.toDataURL('image/jpeg',.82));bitmap.close();setName(file.name);stop();}catch{setError('This image could not be decoded. Try JPEG, PNG, or WebP.');}finally{setLoading(false);if(input.current)input.current.value='';}}
 const choices=record.findings.filter(f=>f.checkId===target);
 return <div className="modal-backdrop" onClick={onClose}><section className="modal camera-modal" role="dialog" aria-modal="true" aria-labelledby="camera-title" onClick={e=>e.stopPropagation()}><header><div><span className="eyebrow">INSPECTION EVIDENCE</span><h2 id="camera-title">Add a photo</h2></div><button className="icon-button" onClick={onClose} aria-label="Close camera"><X size={20}/></button></header><div className="camera-preview">{preview?<img src={preview} alt="Photo preview — not yet saved"/>:<><video ref={video} playsInline muted/>{!ready&&<div className="camera-placeholder"><Camera size={38}/><p></p><button className="primary" onClick={openCamera} disabled={loading}>{loading?'Opening camera…':'Open camera'}</button><small></small></div>}</>}</div>{error&&<p className="error" role="alert"><AlertCircle size={16}/>{error}</p>}<div className="camera-actions">{preview?<button onClick={()=>{setPreview('');setError('');}}><RotateCcw size={16}/>Retake / choose another</button>:<button className="primary" onClick={capture} disabled={!ready}><Camera size={16}/>Capture photo</button>}<button onClick={()=>input.current?.click()} disabled={loading}><Upload size={16}/>Upload photo</button><input ref={input} type="file" accept="image/*" hidden onChange={e=>upload(e.target.files?.[0])}/></div><details className="camera-association"><summary>{checkById(target).name}{finding?' · '+choices.find(f=>f.id===finding)?.type:''}</summary><label>Check<select value={target} onChange={e=>{setTarget(e.target.value);setFinding('');}}>{CHECKS.map(c=><option key={c.id} value={c.id}>{c.name} · {c.section}</option>)}</select></label><label>Finding<select value={finding} onChange={e=>setFinding(e.target.value)}><option value="">General check evidence</option>{choices.map(f=><option key={f.id} value={f.id}>{f.type} · {f.notes}</option>)}</select></label></details><p className="muted small">{preview?'Say “save photo” or “retake”.':'Say “capture” when ready.'}</p><footer><button onClick={onClose}>Cancel</button><button className="primary" disabled={!preview||loading} onClick={()=>{onSave({id:uid(),checkId:target,findingId:finding||undefined,data:preview,name:name||checkById(target).name,createdAt:now()});onClose();}}><Check size={16}/>Attach photo</button></footer></section></div>;
}
